# Generated by Django 5.0 on 2023-12-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='format: required', verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='product name'),
        ),
    ]
