# Generated by Django 5.0 on 2023-12-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_product_name_gin_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='name_gin_index',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='description_gin_index',
        ),
    ]
