# Generated by Django 5.0 on 2023-12-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_name_gin_index_name_gin_trgm_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='name_gin_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='description_gin_trgm_idx',
        ),
    ]
